env:
    browser: true
    es2021: true
  
extends:
    - plugin:vue/vue3-strongly-recommended
    - airbnb-base

parserOptions:
    ecmaVersion: latest
    sourceType: module

rules:
    indent:
        - error
        - 4
    vue/html-indent:
        - error
        - 4
    vue/multi-word-component-names:
        - off
    vue/max-attributes-per-line:
        - off
    import/prefer-default-export:
        - off
    no-plusplus:
        - off
    no-await-in-loop:
        - off
    no-externaous-dependencies:
        - off